apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  labels:
    app: save-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: save-employee
  template:
    metadata:
      labels:
        app: save-employee
        tier: compute
    spec:
      containers:
        - image: employee-api
          name: employee-api
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbname
                  
            - name: CLOUDANT_URL
              valueFrom:
                secretKeyRef:
                  name: binding-cloudant-demo
                  key: url
            - name: CLOUDANT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: binding-cloudant-demo
                  key: username
            - name: CLOUDANT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: binding-cloudant-demo
                  key: password
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: save-employee
